#!/bin/sh

SCRIPT_NAME="runtest"
VERSION="1.0"
OPTS=$(getopt -o ahv \
    --long all \
    --long help \
    --long version \
    -- "$@")
eval set -- "$OPTS"

while true
do
    case "$1" in
        -a|--all)
            all=1;;
        -h|--help)
            echo -e "Usage: $SCRIPT_NAME [OPTION]...\n"
            echo -e "Run SameGame tests."
            echo "List of possible options:"
            echo -e "\t-a, --all\ttest on all available test cases"
            echo -e "\t-h, --help\tprint this help"
            echo -e "\t-v, --version\tshow version info"
            exit;;
        -v|--version)
            echo "$SCRIPT_NAME (script) $VERSION"
            echo "Written by Hubert Obrzut"
            exit;;
        --) shift; break;;
    esac
    shift
done

get_test_nr() {
    name="$1"
    name="${name%%\.txt}"
    nr="${name##tests/testcase}"
    echo $nr
}

get_result_dir() {
    testcase="$1"
    testnr=$(get_test_nr "$testcase")
    echo results/result$testnr.txt
}

exename="samegame"
testdir="tests"

if [ -n "$all" ]; then
    echo "Running all the tests!"
    # make clean && make release
    for testfile in $testdir/*.txt; do
        if [ $(get_test_nr $testfile ) -gt 20 ]; then
            continue
        fi
        echo $testfile
        ./"$exename" < $testfile > $(get_result_dir "$testfile")
    done 
else
    [ $# = 1 ] || {
        echo "ERROR: usage: $SCRIPT_NAME [OPTIONS...] [TESTCASE]" 1>&2
        exit 1
    }
    testcase="$1"
    echo "Running $testcase test!"
    make
    ./"$exename" < "tests/testcase$testcase.txt"
fi

